// Copyright 2016 Open Source Robotics Foundation, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// (c) 2021 Copyright, Real-Time Innovations, Inc.  All rights reserved.
//
// RTI grants Licensee a license to use, modify, compile, and create derivative
// works of the Software.  Licensee has the right to distribute object form
// only for use with RTI products.  The Software is provided "as is", with no
// warranty of any type, including any warranty for fitness for any purpose.
// RTI is under no obligation to maintain or support the Software.  RTI shall
// not be liable for any incidental or consequential damages arising out of the
// use or inability to use the software.

// Include RTI Connext DDS "modern C++" API
#include <dds/dds.hpp>
#include <rti/core/ListenerBinder.hpp>

#include <memory>

#include "rclcpp/rclcpp.hpp"

// Include type support code generated by rtiddsgen
#include "std_msgs/msg/String.hpp"

using std::placeholders::_1;

namespace rti { namespace connext_nodes_cpp {

class DdsListener : public rclcpp::Node,
  public dds::sub::NoOpDataReaderListener<std_msgs::msg::String>
{
public:
  DdsListener()
  : Node("dds_listener")
  {
    // The DomainParticipant is created on domain 0 by default
    auto participant = dds::domain::find(0);
    assert(dds::core::null != participant);
    // Create a DataReader for topic "rt/chatter"
    auto subscriber = dds::sub::Subscriber(participant);
    auto topic = dds::topic::Topic<std_msgs::msg::String>(participant,
      "rt/chatter", "std_msgs::msg::dds_::String_");
    dds::sub::qos::DataReaderQos reader_qos; 
    reader_qos << dds::core::policy::Reliability::Reliable();
    reader_ = dds::sub::DataReader<std_msgs::msg::String>(
      subscriber, topic, reader_qos, this, dds::core::status::StatusMask::all());
  }
  void on_data_available(dds::sub::DataReader<std_msgs::msg::String> &reader)
  {
    dds::sub::LoanedSamples<std_msgs::msg::String> samples = reader.take();
    for (auto it = samples.begin(); it != samples.end(); it++)
    {
      if (it->info().valid()) {
        const std_msgs::msg::String& msg = it->data();
        RCLCPP_INFO(this->get_logger(),
          "I heard from Connext: [%s]", msg.data().c_str());
      }
    }
  }

private:
  dds::sub::DataReader<std_msgs::msg::String> reader_{nullptr};
};

}  // namespace connext_nodes_cpp
}  // namespace rti

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<rti::connext_nodes_cpp::DdsListener>());
  rclcpp::shutdown();
  return 0;
}
